[graph]
targets = [
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc",
  "aarch64-unknown-linux-gnu",
  "i686-pc-windows-msvc",
  "i686-unknown-linux-gnu",
  "x86_64-pc-windows-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-errors"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-frontend"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-http"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-listener"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-runtime"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-service"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-temp"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-app-support-tracing"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-cli"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-accounts"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-errors"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-messages"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-permissions"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-sessions"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-slash"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-stream"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-contracts-workspaces"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-mock"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-orchestrator"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
crate = "acp-web-backend"
