[toolchain]
# renovate: datasource=github-tags depName=rust-lang/rust versioning=semver
channel = "1.94.1"
components = ["clippy", "llvm-tools-preview", "rustfmt"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
